# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 09b40b949b1c27007a930e6acae1575b8fad6273e94f2e2f0da0dec85cc5ed9877eb0facf2b08ddc882e05076be3fd56e4ff205a24b087bd56fa6672d6c65078

test:
  secret_key_base: 7c31f874b48fba403380d8a15c12b9e1812d0c78bf2529ba07cc879e672b172835116f6bf1e7a787bffa8d3018eed570a6a21477622e6144837eb7fe7f96bb86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
